pipeline:
  name: test-gar
  identifier: testgar
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: testing-gar-plugin
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Plugin
                  name: Plugin_1
                  identifier: Plugin_1
                  spec:
                    connectorRef: harnessnew
                    image: harnesscommunity/drone-google-artifact-registry:1.0.0
                    settings:
                      google_application_credentials: <+secrets.getValue("key.json")>
                      repository: test-harness
                      location: us-central1
                      service_account_email: dhruba@commeng-play.iam.gserviceaccount.com
                      project_id: commeng-play
                      format: apt
                      file: apt-dpkg-ref_5.3.1+nmu2_all.deb
